version: 2
jobs:
  test:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
  apijob:
    docker:
      - image: debian:stretch
    workflows:
      - test
      - build:
          requires:
            - test

workflows:
  version: 2
  default:
    jobs:
      - test
      - build:
          requires:
            - test