version: 2
jobs:
  test:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
  # apijob:
  #   # version: 2
  #   docker:
  #     - image: debian:stretch
  #   steps:
  #     - run: echo "hello?"
  #   # workflows:
  #   #   - test
  #   #   - build:
  #   #       requires:
  #   #         - test

workflows:
  version: 2
  default:
    jobs:
      - test
      - build:
          requires:
            - test
  onlyapi:
    jobs:
      - test:
          filters:
            tags:
              only: /^e2e-.*/
            branches:
              ignore: /.*/
      - build:
          filters:
            tags:
              only: /^e2e-.*/
            branches:
              ignore: /.*/
          requires:
            - test